apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aap.fullname" . }}-users
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aap.labels" . | nindent 4 }}
data:
  accounts: |
    admin:
      enabled: true
      role: admin
